STOP REPLICA;

CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='master',
  SOURCE_USER='repl',
  SOURCE_PASSWORD='slavepass',
  SOURCE_PORT=3306,
  SOURCE_SSL=0;
  SOURCE_LOG_FILE='mysql-bin.000008',
  SOURCE_LOG_POS=545;

START REPLICA;

SHOW SLAVE STATUS\G